### ISSUE TITLE
Oops VFS connection does not exist

### ISSUE THREAD

**Issue by add-more-tabasco** [saasbook/hw-rails-intro#22]
I am at this step:  

> If you are using c9, use rails s -p $PORT -b $IP and navigate to the link generated within c9.

The link that pops up in cloud9 opens a page saying only Oops VFS connection does not exist.

**Comment by tansaku** [comment]
that's weird ...

**Comment by add-more-tabasco** [comment]
This is an issue with firefox and/or the C9 IDE, not the course. Sorry I rushed to post it as an issue here.

**Comment by tansaku** [comment]
no worries :-)
