### ISSUE TITLE
codio/bundler issue

### ISSUE THREAD

**Issue by tansaku** [saasbook/hw-rails-intro#23]
Susan reported:

> I'm using Codio this semester, and was building the empty Rails app from chapter 4, ran "rails new myrottenpotatoes -T", got this error message:

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (= 4.2.10) was resolved to 4.2.10, which depends on
      bundler (< 2.0, >= 1.3.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (< 2.0, >= 1.3.0)', which is required by gem 'rails (= 4.2.10)', in any of the sources.
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
         run bundle exec spring binstub --all
Bundler 2 requires Ruby 2.3 or later. Either install bundler 1 or update to a supported Ruby version.
```
> Just to let everyone know that there may be version conflicts now that Bundler has dropped version 2.0.1.  I had issues with HW2 and Bundler and Heroku.  See the conference call video from 2/4/19 for further discussion.

**Comment by jsfrench** [comment]
Just to let you know, AWS C9 is on bundler 2.0.1 also, and the same issue arises.

**Comment by tansaku** [comment]
Max from Codio suggested this approach to set bundler within rvm:

```
rvm @global do gem uninstall bundler
rvm @global do gem install bundler -v 1.7.1
```

**Comment by jsfrench** [comment]
I think the above should refer to 1.17.1, not 1.7.1?
 i.e.
```
rvm @global do gem uninstall bundler
rvm @global do gem install bundler -v 1.17.1
```

The latest pre-2.0 release of Bundler is [1.17.3](https://github.com/bundler/bundler/releases/tag/v1.17.3), maybe we should be using this?

**Comment by jsfrench** [comment]
FYI `@global` doesn't work on AWS C9. 

`ERROR: While executing gem ... (Gem::FilePermissionError) You don't have write permissions for the /usr/local/rvm/gems/ruby-2.4.1@global/bin directory.`

But this seems to work fine:
```
rvm all do gem uninstall bundler
rvm all do gem install bundler -v 1.17.1
```
