### ISSUE TITLE
sqlite issue

### ISSUE THREAD

**Issue by tansaku** [saasbook/hw-rails-intro#24]
Susan reported:

> Now I'm having issues with my version of sqlite3.  When I try to run rottenpotatoes, I get this error: 
```Specified 'sqlite3' for database adapter, but the gem is not loaded. Add `gem 'sqlite3'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).```
> I'm using the Gemfile that is included with the app in Github which specifies gem sqlite3.  
> The Gemfile just calls for sqlite3 with no version number.  Codio has sqlite3 version 3.8.2 engine installed.  Could I have a version conflict?  

and found she was able to fix it by locking the sqlite gem to 1.3.13

**Comment by kingdish** [comment]
Should be fixed in an earlier version
