### ISSUE TITLE
missing codio instructions

### ISSUE THREAD

**Issue by mverdicchio** [saasbook/hw-rails-intro#26]
https://github.com/saasbook/hw-rails-intro/blob/master/docs/part_0_A.md

On Codio, students must add the line `config.hosts = nil` to `config/environments/development.rb`, change the preview static button to box URL, and run rails server with the command `rails server -b 0.0.0.0`. These instructions are present (with screenshots) in the former Codio version of the instructions but are missing here.

**Comment by kingdish** [comment]
Should have been fixed in an earlier version
