### ISSUE TITLE
Some possible changes to the instructions?

### ISSUE THREAD

**Issue by tansaku** [saasbook/hw-rails-intro#6]
From one of the SPOC instructors:

  Before we could run git push heroku master:
 — The instructions for getting set up on Heroku did not include setting up the keys.  We had to use heroku keys:add ~/.ssh/id_rsa.pub
 — We needed to use git remote add heroku git@heroku.com:<name>.git

 Tests:
 — We had to run bundle install before we could run autotest 
 — odd errors in autotest on pending tests
 — there seems to be an error on the third test for context ‘incorrectly’ - it appears to be looking for valid to be true when the guess is not correct

Perhaps some of these things should be added to the instructions.

**Comment by tansaku** [comment]
of course the interesting question is how much detail should instructions go into - are they precise walkthroughs that you can follow without any thought, or are these things challenges to be overcome as part of the assignment?

**Comment by tansaku** [comment]
this was on the wrong repo - moved to https://github.com/saasbook/hw-sinatra-saas-hangperson/issues/12

**Comment by armandofox** [comment]
i'd prefer steps that say WHAT to do and give a pointer to docs, but not explicit copy-paste instructions.

eg:

1) Follow Heroku's instructions [include link] for installing the Toolbelt in your IDE (or Cloud9), including creating keys for deployment and creating a Heroku app "container" that will eventually host your deployed app.

2) Don't forget when starting to work with a new project or adding gems to an existing project that you must run `bundle` to ensure all the correct versions of necessary gems are installed.

etc.

Armando Fox
Professor, Computer Science Division
Faculty Advisor, UC Berkeley MOOCLab
fox .at. cs .dot. berkeley .dot. edu
581 Soda Hall MC#1776, Berkeley, CA 94720-1776
+1.510.642.6820 / http://www.cs.berkeley.edu/~fox

TAKE MY CLASS FOR FREE VIA edX:  http://saas-class.org  
LIKE IT ON FACEBOOK:  http://facebook.com/saas-class
TRY MY BOOK (NOT FREE): http://www.saasbook.info (goes with the course)
